#!/usr/bin/env bash
# Archivo de referencia rápida para iniciar el proyecto

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          iCarSolutions - QUICK START SCRIPT              ║"
echo "║         Plataforma de Venta de Vehículos Full-Stack       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 PASOS PARA INICIAR:"
echo ""
echo "1️⃣  LEE PRIMERO (1 minuto)"
echo "   cat START_HERE.md"
echo ""
echo "2️⃣  SETUP RÁPIDO (5 minutos)"
echo "   cat QUICKSTART.md"
echo ""
echo "3️⃣  BACKEND (Terminal 1)"
echo "   cd backend"
echo "   cp .env.example .env"
echo "   # Edita .env con credenciales de Supabase"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "4️⃣  FRONTEND (Terminal 2)"
echo "   cd frontend"
echo "   cp .env.example .env"
echo "   # Edita .env con credenciales de Supabase"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "5️⃣  OPEN BROWSER"
echo "   http://localhost:3000"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTACIÓN:"
echo "   START_HERE.md           ← Inicio (HAS AQUÍ PRIMERO)"
echo "   QUICKSTART.md           ← 5 minutos de setup"
echo "   README.md               ← Documentación completa"
echo "   SETUP_INSTRUCTIONS.md   ← Paso a paso detallado"
echo "   DIAGRAMA-SISTEMA.md     ← Cómo funciona la app"
echo "   DEPLOYMENT.md           ← Cómo deployar a producción"
echo "   TECHNICAL_SPECS.md      ← Referencia técnica"
echo "   PROJECT_SUMMARY.md      ← Resumen del proyecto"
echo ""
echo "📁 ESTRUCTURA:"
echo "   backend/     → API REST (Node.js + Express)"
echo "   frontend/    → Web (Astro + React)"
echo ""
echo "🔗 LINKS RÁPIDOS:"
echo "   Local Frontend: http://localhost:3000"
echo "   Local Backend:  http://localhost:3000/api/health"
echo "   Supabase:       https://supabase.com"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✨ ¡Tu proyecto iCarSolutions está listo para usar! ✨"
echo ""
